### ISSUE TITLE
[Layout] Changes to the topbar

### ISSUE THREAD

**Issue by mairatma** [inloco/orion#162]
Some requested changes to the Topbar:
- [ ] The logo should be smaller.
- [x] Menu items can have icons on the left. (was already done)

See the screenshot below:
<img width="1440" alt="Screen Shot 2019-08-14 at 10 26 22 AM" src="https://user-images.githubusercontent.com/5216049/63024630-fc9f5280-be7d-11e9-931b-a5b870a7bc53.png">

**Comment by FranciscoGileno** [comment]
About this one:
`Menu items can have icons on the left.`

We can already accomplish this:

```
<Menu.Item>
  <Icon name="location_on" className="mr-4" />
  Places
</Menu.Item>
```

Do you think we need a better interface?

**Comment by mairatma** [comment]
Nope, I thought that it wouldn't look nice yet, I didn't remember styling menu items with the icons, so I thought we still needed to do it. If it's looking good, then we just need to update the logo size.

**Comment by mairatma** [comment]
Oh actually, now that I see your code, I think it'd be best to allow something like `<Menu.Item icon="location_on" name="Places" />`, so that the margin size doesn't have to be repeated everywhere (and possibly gotten wrong, specially if design wants to change it someday).

**Comment by mairatma** [comment]
I've finally checked the code and this interface I've suggested already works, so it's really just the logo here :)

**Comment by mairatma** [comment]
Gileno did this.
