### ISSUE TITLE
[Dropdown]: Keep showing placeholder if input text is empty (even with selected labels)

### ISSUE THREAD

**Issue by mairatma** [inloco/orion#163]
We correctly show the placeholder when the input text is empty and there are no selected labels, like this:
<img width="428" alt="Screen Shot 2019-08-14 at 10 28 05 AM" src="https://user-images.githubusercontent.com/5216049/63024772-49832900-be7e-11e9-8c52-88e7c617771a.png">

But, when at least one label is selected, we stop showing the placeholder, even when there's no text:
<img width="419" alt="Screen Shot 2019-08-14 at 10 28 08 AM" src="https://user-images.githubusercontent.com/5216049/63024773-49832900-be7e-11e9-9c7a-5ef6255e69a9.png">

We should keep showing the placeholder in this case.

**Comment by FranciscoGileno** [comment]
I am not sure if this should be the right behaviour.

Usually placeholders are shown only if the field is empty which is not the case.

This same component in Semantic UI does not show the placeholder after one or more options are selected.

https://react.semantic-ui.com/modules/dropdown/#types-multiple-selection

What do you think @mairatma ?

**Comment by mairatma** [comment]
Weird, I was sure that semantic ui did this. From what I remember I saw it there and thought this was how it was supposed to be, so I created the issue. But I've checked again now and you're right, it doesn't show up. Not sure if this changed or if I was just crazy that day... Let's close!
