### ISSUE TITLE
New component: Pagination

### ISSUE THREAD

**Issue by mairatma** [inloco/orion#235]
Ainda não temos um componente de paginação. No `semantic-ui-react` ele é o [`Pagination`](Pagination).

<img width="522" alt="Screen Shot 2019-09-19 at 9 15 43 AM" src="https://user-images.githubusercontent.com/5216049/65243117-14da4100-dabe-11e9-87a5-5f5a038c6567.png">

**Comment by FranciscoGileno** [comment]
I will work on this one.

Since it is so different from the semantic-ui pagination, I believe it will easier if we build one from scratch...

**Comment by mairatma** [comment]
@FranciscoGileno tu já terminou né? Já dá pra fechar aqui?
