### ISSUE TITLE
New component: Dialog

### ISSUE THREAD

**Issue by mairatma** [inloco/orion#236]
Esse é um tipo de `Modal`, mas em um estilo diferente do nosso `Modal`, que já está pronto. Temos que ver se fará mais sentido ser apenas um tipo passado por prop ou se seria acessado por um alias como `Dialog` por exemplo (mas mesmo se for assim imagino teria que ter a versão com prop pra aproveitarmos o comportamento do Modal que já existe ao menos).

Imagem do Invision:
<img width="812" alt="Screen Shot 2019-09-19 at 9 16 47 AM" src="https://user-images.githubusercontent.com/5216049/65243278-6edb0680-dabe-11e9-89d2-d9a13136d824.png">

**Comment by marcelscr** [comment]
Adicionado no PR https://github.com/inloco/orion/pull/318.
