### ISSUE TITLE
[Dropdown] Possibility to set menu direction to right

### ISSUE THREAD

**Issue by FranciscoGileno** [inloco/orion#256]
Semantic UI already has the functionality to set menu direction to right:
![image](https://user-images.githubusercontent.com/1139664/66216827-8f998380-e69c-11e9-91b2-77573578266e.png)
https://react.semantic-ui.com/modules/dropdown/#variations-menu-direction

However, Orion does not have the styles for this behaviour yet and we already need it on UserProfile inside our products:

![image](https://user-images.githubusercontent.com/1139664/66217106-13537000-e69d-11e9-9b93-a7afc44532cf.png)

**Comment by hcaula** [comment]
Solved by https://github.com/inloco/orion/pull/263!
