### ISSUE TITLE
Input not working when used with an icon and a given width

### ISSUE THREAD

**Issue by llaryssa** [inloco/orion#432]
code: `<Input className="w-1/2" icon="search" />`

result: 
![Screen Shot 2020-01-15 at 13 12 59](https://user-images.githubusercontent.com/4022430/72450285-d8330380-3798-11ea-83f4-1ff8cc25d1b5.png)

the icon is correct, but the input component is not. adding a `width: 100%` in the input should work.

**Comment by mairatma** [comment]
Feito.
