### ISSUE TITLE
Search is not working with fluid

### ISSUE THREAD

**Issue by llaryssa** [inloco/orion#433]
code: `<Search fluid icon="search" />`

result: 
![Screen Shot 2020-01-15 at 13 16 08](https://user-images.githubusercontent.com/4022430/72450560-55f70f00-3799-11ea-8bba-ee9778a2c30f.png)

the component should occupy the full width of the page.
I think maybe the css is just not done yet.

**Comment by mairatma** [comment]
Corrigi com este pr: https://github.com/inloco/orion/pull/517.
